/* Generated by pnpm contracts. Do not edit. */

export type Id = string;
export type Page = string;
export type Anchor = string;
export type Kind = "paragraph" | "code" | "table_row" | "image";
export type Text = string;
export type StartLine = number;
export type StartColumn = number;
export type EndLine = number;
export type EndColumn = number;
export type Kind1 = "identifier" | "url" | "path" | "flag";
export type Value = string;
export type References = Reference[];
export type Language = string | null;
export type Runnable = boolean;
export type Session = string | null;
export type ExpectedOutput = string | null;
export type ClaimStatus = "unknown" | "verified" | "stale" | "unverifiable";
export type LastVerified = string | null;
export type VerificationMethod = string | null;
/**
 * @maxItems 10000
 */
export type Claims = Claim[];
export type Path = string;
export type Content = string;
/**
 * @maxItems 2000
 */
export type Before = SourceFile[];
/**
 * @maxItems 2000
 */
export type After = SourceFile[];

export interface AnalysisRequest {
  claims: Claims;
  before: Before;
  after: After;
}
export interface Claim {
  id: Id;
  page: Page;
  anchor: Anchor;
  kind: Kind;
  text: Text;
  position: Position;
  references?: References;
  language?: Language;
  runnable?: Runnable;
  session?: Session;
  expected_output?: ExpectedOutput;
  status?: ClaimStatus;
  last_verified?: LastVerified;
  verification_method?: VerificationMethod;
}
export interface Position {
  start_line: StartLine;
  start_column: StartColumn;
  end_line: EndLine;
  end_column: EndColumn;
}
export interface Reference {
  kind: Kind1;
  value: Value;
}
export interface SourceFile {
  path: Path;
  content: Content;
}
