/* Generated by pnpm contracts. Do not edit. */

export type SchemaVersion = string;
export type Id = string;
export type Page = string;
export type Anchor = string;
export type Kind = "paragraph" | "code" | "table_row" | "image";
export type Text = string;
export type StartLine = number;
export type StartColumn = number;
export type EndLine = number;
export type EndColumn = number;
export type Kind1 = "identifier" | "url" | "path" | "flag";
export type Value = string;
export type References = Reference[];
export type Language = string | null;
export type Runnable = boolean;
export type Session = string | null;
export type ExpectedOutput = string | null;
export type ClaimStatus = "unknown" | "verified" | "stale" | "unverifiable";
export type LastVerified = string | null;
export type VerificationMethod = string | null;
export type Claims = Claim[];
export type Id1 = string;
export type Path = string;
export type Name = string;
export type QualifiedName = string;
export type Kind2 = string;
export type Language1 = string;
export type StartLine1 = number;
export type EndLine1 = number;
export type Fingerprint = string;
export type Symbols = Symbol[];
export type ClaimId = string;
export type SymbolId = string;
export type Match = string;
export type Confidence = number;
export type Links = ClaimLink[];
export type ChangedSymbolIds = string[];
export type ClaimId1 = string;
export type SymbolIds = string[];
export type Reason = string;
export type Impacts = Impact[];
export type TotalClaims = number;
export type LinkedClaims = number;
export type AffectedClaims = number;
export type LinkCoverage = number;
export type VerifiedShare = number;
export type Warnings = string[];

export interface AnalysisReport {
  schema_version?: SchemaVersion;
  claims: Claims;
  symbols: Symbols;
  links: Links;
  changed_symbol_ids: ChangedSymbolIds;
  impacts: Impacts;
  health: Health;
  warnings: Warnings;
}
export interface Claim {
  id: Id;
  page: Page;
  anchor: Anchor;
  kind: Kind;
  text: Text;
  position: Position;
  references?: References;
  language?: Language;
  runnable?: Runnable;
  session?: Session;
  expected_output?: ExpectedOutput;
  status?: ClaimStatus;
  last_verified?: LastVerified;
  verification_method?: VerificationMethod;
}
export interface Position {
  start_line: StartLine;
  start_column: StartColumn;
  end_line: EndLine;
  end_column: EndColumn;
}
export interface Reference {
  kind: Kind1;
  value: Value;
}
export interface Symbol {
  id: Id1;
  path: Path;
  name: Name;
  qualified_name: QualifiedName;
  kind: Kind2;
  language: Language1;
  start_line: StartLine1;
  end_line: EndLine1;
  fingerprint: Fingerprint;
}
export interface ClaimLink {
  claim_id: ClaimId;
  symbol_id: SymbolId;
  match: Match;
  confidence: Confidence;
}
export interface Impact {
  claim_id: ClaimId1;
  symbol_ids: SymbolIds;
  reason: Reason;
}
export interface Health {
  total_claims: TotalClaims;
  linked_claims: LinkedClaims;
  affected_claims: AffectedClaims;
  link_coverage: LinkCoverage;
  verified_share: VerifiedShare;
  statuses: Statuses;
}
export interface Statuses {
  [k: string]: number;
}
