/* Generated by pnpm contracts. Do not edit. */

export type MaxPages = number;
export type MaxPrs = number;
export type MaxLinesChanged = number;

export interface ChangeBudget {
  max_pages?: MaxPages;
  max_prs?: MaxPrs;
  max_lines_changed?: MaxLinesChanged;
}
