/* Generated by pnpm contracts. Do not edit. */

export type TimeoutSeconds = number;
export type MemoryMb = number;
export type OutputBytes = number;
export type MaxBlocks = number;

export interface SandboxLimits {
  timeout_seconds?: TimeoutSeconds;
  memory_mb?: MemoryMb;
  output_bytes?: OutputBytes;
  max_blocks?: MaxBlocks;
}
