/* Generated by pnpm contracts. Do not edit. */

export type SchemaVersion = string;
export type Id = string;
export type CreatedAt = string;
export type SourceDigest = string;
export type Image = string;
export type Id1 = string;
export type Page = string;
export type Anchor = string;
export type Kind = "paragraph" | "code" | "table_row" | "image";
export type Text = string;
export type StartLine = number;
export type StartColumn = number;
export type EndLine = number;
export type EndColumn = number;
export type Kind1 = "identifier" | "url" | "path" | "flag";
export type Value = string;
export type References = Reference[];
export type Language = string | null;
export type Runnable = boolean;
export type Session = string | null;
export type ExpectedOutput = string | null;
export type ClaimStatus = "unknown" | "verified" | "stale" | "unverifiable";
export type LastVerified = string | null;
export type VerificationMethod = string | null;
export type Claims = Claim[];
export type Id2 = string;
export type ClaimId = string;
export type ClaimDigest = string;
export type SourceDigest1 = string;
export type Method = "python_execution";
export type Outcome = "passed" | "failed" | "error" | "skipped";
export type ClaimStatus1 = "unknown" | "verified" | "stale" | "unverifiable";
export type Reason = string;
export type StartedAt = string;
export type FinishedAt = string;
export type ImageId = string | null;
export type ExitCode = number | null;
export type Stdout = string;
export type Stderr = string;
export type ExpectedOutput1 = string | null;
export type TimeoutSeconds = number;
export type MemoryMb = number;
export type OutputBytes = number;
export type MaxBlocks = number;
export type Evidence = VerificationEvidence[];

export interface VerificationReport {
  schema_version?: SchemaVersion;
  id: Id;
  created_at: CreatedAt;
  source_digest: SourceDigest;
  image: Image;
  claims: Claims;
  evidence: Evidence;
  outcomes: Outcomes;
  statuses: Statuses;
}
export interface Claim {
  id: Id1;
  page: Page;
  anchor: Anchor;
  kind: Kind;
  text: Text;
  position: Position;
  references?: References;
  language?: Language;
  runnable?: Runnable;
  session?: Session;
  expected_output?: ExpectedOutput;
  status?: ClaimStatus;
  last_verified?: LastVerified;
  verification_method?: VerificationMethod;
}
export interface Position {
  start_line: StartLine;
  start_column: StartColumn;
  end_line: EndLine;
  end_column: EndColumn;
}
export interface Reference {
  kind: Kind1;
  value: Value;
}
export interface VerificationEvidence {
  id: Id2;
  claim_id: ClaimId;
  claim_digest: ClaimDigest;
  source_digest: SourceDigest1;
  method?: Method;
  outcome: Outcome;
  status: ClaimStatus1;
  reason: Reason;
  started_at: StartedAt;
  finished_at: FinishedAt;
  image_id?: ImageId;
  exit_code?: ExitCode;
  stdout?: Stdout;
  stderr?: Stderr;
  expected_output?: ExpectedOutput1;
  limits: SandboxLimits;
}
export interface SandboxLimits {
  timeout_seconds?: TimeoutSeconds;
  memory_mb?: MemoryMb;
  output_bytes?: OutputBytes;
  max_blocks?: MaxBlocks;
}
export interface Outcomes {
  [k: string]: number;
}
export interface Statuses {
  [k: string]: number;
}
