import { readFile, writeFile } from "node:fs/promises";
import { compile } from "json-schema-to-typescript";

for (const name of [
  "Claim",
  "AnalysisRequest",
  "AnalysisReport",
  "ChangeBudget",
  "SandboxLimits",
  "VerificationReport",
]) {
  const schema = JSON.parse(await readFile(`packages/contracts/src/${name}.schema.json`, "utf8"));
  await writeFile(
    `packages/contracts/src/${name}.generated.ts`,
    await compile(schema, name, {
      bannerComment: "/* Generated by pnpm contracts. Do not edit. */",
    }),
  );
}
